[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
membership_core = "3Ne2f2pLbgpsWL3v9xCDy6VjKmoqHjbBtEJL3a6tMuCs"

[programs.devnet]
membership_core = "3Ne2f2pLbgpsWL3v9xCDy6VjKmoqHjbBtEJL3a6tMuCs"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/proofmembership/admin.json"
